namespace: zpe
name: zpecloud
version: 1.0.2
description: An Ansible collection to communicate with Nodegrid devices via ZPE Cloud
authors:
  - Rene Neumann <rene.neumann@zpesystems.com>
  - Leonardo Fernandes <leonardo.fernandes@zpesystems.com>
  - Daniel Nesvera <daniel.nesvera@zpesystems.com>
tags: [zpe, zpesystems, zpecloud, nodegrid, ng, nodegridos, management, networking, security, cloud]
license_file: LICENSE
readme: README.md
repository: https://github.com/ZPESystems/zpe.zpecloud
homepage: https://zpesystems.com
issues: https://github.com/ZPESystems/zpe.zpecloud/issues